/*
 * JSP generated by Resin-3.1.12 (built Mon, 29 Aug 2011 03:22:08 PDT)
 */

package _jsp._sy._comm._desk;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import com.rh.core.base.Context;
import com.rh.core.base.Bean;
import com.rh.core.org.UserBean;
import com.rh.core.serv.util.ServUtils;
import com.rh.core.util.RequestUtils;
import com.rh.core.util.Constant;
import com.rh.core.util.JsonUtils;
import com.rh.core.util.var.VarMgr;
import com.rh.core.util.device.DeviceUtils;

public class _desk__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
    final String CONTEXT_PATH = request.getContextPath();

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	request.setCharacterEncoding("UTF-8");
	Context.setRequest(request);
	String urlPath = request.getContextPath();
    UserBean userBean = Context.getUserBean(request);
    String devUsers = Context.getSyConf("SY_DEV_USERS","");//\u5f00\u53d1\u7528\u6237
    String syFont = Context.getSyConf("SY_FONT_BIG","false");//\u7cfb\u7edf\u5927\u5b57\u4f53\u542f\u7528
    String zipModel = Context.getSyConf("SY_FRONT_ZIP_MODEL","false");//\u524d\u7aef\u6587\u4ef6\u662f\u5426\u542f\u7528\u538b\u7f29\u6a21\u5f0f
    String pjJS = Context.getSyConf("SY_PJ_JS","");//\u9879\u76ee\u7ea7\u81ea\u6269\u5c55js
    String pjCSS = Context.getSyConf("SY_PJ_CSS","");//\u9879\u76ee\u7ea7\u81ea\u6269\u5c55css
    String pjTop = Context.getSyConf("SY_PJ_TOPVIEW","");//\u9879\u76ee\u7ea7\u5361\u7247\u5217\u8868\u9876\u90e8\u7684\u533a\u5757\u663e\u793a
    String dev = "";
    if (request != null) {
        dev = DeviceUtils.getCurrentDevice(request).getDeviceType().toString();
    }   

      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((System.getProperty("servName")));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      if (dev.equals("MOBILE")){
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((urlPath ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      } else if (dev.equals("TABLET")) {
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((urlPath ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      } else {
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((urlPath ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      }
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((urlPath));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      if (zipModel.equals("true")) {
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((urlPath ));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((urlPath ));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      if (syFont.equals("true")) {
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((urlPath ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      } 
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((urlPath ));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((urlPath ));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((urlPath ));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((urlPath ));
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((urlPath ));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print((urlPath ));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      if (dev.equals("DESKTOP")){
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((urlPath ));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      } else {
      out.write(_jsp_string26, 0, _jsp_string26.length);
      out.print((urlPath ));
      out.write(_jsp_string27, 0, _jsp_string27.length);
      out.print((urlPath ));
      out.write(_jsp_string28, 0, _jsp_string28.length);
      }
      out.write(_jsp_string29, 0, _jsp_string29.length);
      } else {
      out.write(_jsp_string30, 0, _jsp_string30.length);
      out.print((urlPath ));
      out.write(_jsp_string31, 0, _jsp_string31.length);
      out.print((urlPath ));
      out.write(_jsp_string32, 0, _jsp_string32.length);
      out.print((urlPath ));
      out.write(_jsp_string33, 0, _jsp_string33.length);
      out.print((urlPath ));
      out.write(_jsp_string34, 0, _jsp_string34.length);
      out.print((urlPath ));
      out.write(_jsp_string35, 0, _jsp_string35.length);
      out.print((urlPath ));
      out.write(_jsp_string36, 0, _jsp_string36.length);
      out.print((urlPath ));
      out.write(_jsp_string37, 0, _jsp_string37.length);
      out.print((urlPath ));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      out.print((urlPath ));
      out.write(_jsp_string39, 0, _jsp_string39.length);
      out.print((urlPath ));
      out.write(_jsp_string40, 0, _jsp_string40.length);
      if (syFont.equals("true")) {
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((urlPath ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      } 
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((urlPath ));
      out.write(_jsp_string41, 0, _jsp_string41.length);
      out.print((urlPath ));
      out.write(_jsp_string42, 0, _jsp_string42.length);
      out.print((urlPath ));
      out.write(_jsp_string43, 0, _jsp_string43.length);
      out.print((urlPath ));
      out.write(_jsp_string44, 0, _jsp_string44.length);
      out.print((urlPath ));
      out.write(_jsp_string45, 0, _jsp_string45.length);
      out.print((urlPath ));
      out.write(_jsp_string46, 0, _jsp_string46.length);
      out.print((urlPath ));
      out.write(_jsp_string47, 0, _jsp_string47.length);
      out.print((urlPath ));
      out.write(_jsp_string48, 0, _jsp_string48.length);
      out.print((urlPath ));
      out.write(_jsp_string49, 0, _jsp_string49.length);
      out.print((urlPath ));
      out.write(_jsp_string50, 0, _jsp_string50.length);
      out.print((urlPath ));
      out.write(_jsp_string51, 0, _jsp_string51.length);
      out.print((urlPath ));
      out.write(_jsp_string52, 0, _jsp_string52.length);
      out.print((urlPath ));
      out.write(_jsp_string53, 0, _jsp_string53.length);
      out.print((urlPath ));
      out.write(_jsp_string54, 0, _jsp_string54.length);
      out.print((urlPath ));
      out.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((urlPath ));
      out.write(_jsp_string56, 0, _jsp_string56.length);
      out.print((urlPath ));
      out.write(_jsp_string57, 0, _jsp_string57.length);
      out.print((urlPath ));
      out.write(_jsp_string58, 0, _jsp_string58.length);
      out.print((urlPath ));
      out.write(_jsp_string59, 0, _jsp_string59.length);
      out.print((urlPath ));
      out.write(_jsp_string60, 0, _jsp_string60.length);
      out.print((urlPath ));
      out.write(_jsp_string61, 0, _jsp_string61.length);
      out.print((urlPath ));
      out.write(_jsp_string62, 0, _jsp_string62.length);
      out.print((urlPath ));
      out.write(_jsp_string63, 0, _jsp_string63.length);
      out.print((urlPath ));
      out.write(_jsp_string64, 0, _jsp_string64.length);
      out.print((urlPath ));
      out.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((urlPath ));
      out.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((urlPath ));
      out.write(_jsp_string67, 0, _jsp_string67.length);
      out.print((urlPath ));
      out.write(_jsp_string68, 0, _jsp_string68.length);
      out.print((urlPath ));
      out.write(_jsp_string69, 0, _jsp_string69.length);
      out.print((urlPath ));
      out.write(_jsp_string70, 0, _jsp_string70.length);
      out.print((urlPath ));
      out.write(_jsp_string71, 0, _jsp_string71.length);
      out.print((urlPath ));
      out.write(_jsp_string72, 0, _jsp_string72.length);
      out.print((urlPath ));
      out.write(_jsp_string73, 0, _jsp_string73.length);
      out.print((urlPath ));
      out.write(_jsp_string74, 0, _jsp_string74.length);
      out.print((urlPath ));
      out.write(_jsp_string75, 0, _jsp_string75.length);
      out.print((urlPath ));
      out.write(_jsp_string76, 0, _jsp_string76.length);
      out.print((urlPath ));
      out.write(_jsp_string77, 0, _jsp_string77.length);
      out.print((urlPath ));
      out.write(_jsp_string78, 0, _jsp_string78.length);
      out.print((urlPath ));
      out.write(_jsp_string79, 0, _jsp_string79.length);
      out.print((urlPath ));
      out.write(_jsp_string80, 0, _jsp_string80.length);
      out.print((urlPath ));
      out.write(_jsp_string81, 0, _jsp_string81.length);
      out.print((urlPath ));
      out.write(_jsp_string82, 0, _jsp_string82.length);
      out.print((urlPath ));
      out.write(_jsp_string83, 0, _jsp_string83.length);
      out.print((urlPath ));
      out.write(_jsp_string84, 0, _jsp_string84.length);
      if (dev.equals("DESKTOP")){
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((urlPath ));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      } else {
      out.write(_jsp_string26, 0, _jsp_string26.length);
      out.print((urlPath ));
      out.write(_jsp_string27, 0, _jsp_string27.length);
      out.print((urlPath ));
      out.write(_jsp_string28, 0, _jsp_string28.length);
      }
      out.write(_jsp_string29, 0, _jsp_string29.length);
      }
      out.write(_jsp_string85, 0, _jsp_string85.length);
      out.print((urlPath));
      out.write(_jsp_string86, 0, _jsp_string86.length);
      if (pjJS.length() > 0) {
      out.write(_jsp_string87, 0, _jsp_string87.length);
      out.print((urlPath ));
      out.print((pjJS ));
      out.write(_jsp_string88, 0, _jsp_string88.length);
      } 
      out.write(_jsp_string89, 0, _jsp_string89.length);
      if (pjCSS.length() > 0) {
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((urlPath ));
      out.print((pjCSS ));
      out.write(_jsp_string90, 0, _jsp_string90.length);
      } 
      out.write(_jsp_string91, 0, _jsp_string91.length);
      out.print((System.getProperty("servName")==null?"":System.getProperty("servName")));
      out.write(_jsp_string92, 0, _jsp_string92.length);
      out.print((request.getSession().getId()));
      out.write(_jsp_string93, 0, _jsp_string93.length);
      out.print((devUsers));
      out.write(_jsp_string94, 0, _jsp_string94.length);
      if (userBean != null) {
      out.write(_jsp_string95, 0, _jsp_string95.length);
      
				//\u7528\u6237\u76f8\u5173\u4fe1\u606f\u3001\u7cfb\u7edf\u914d\u7f6e\u4fe1\u606f\u3001\u65e5\u671f\u76f8\u5173\u4fe1\u606f
			    String sysParams = JsonUtils.mapsToJson(VarMgr.getOrgMap(), VarMgr.getConfMap(), VarMgr.getDateMap());
			
      out.write(_jsp_string96, 0, _jsp_string96.length);
      out.print((sysParams));
      out.write(_jsp_string97, 0, _jsp_string97.length);
      out.print((userBean.getLoginName()));
      out.write(_jsp_string98, 0, _jsp_string98.length);
      out.print((userBean.getCode()));
      out.write(_jsp_string94, 0, _jsp_string94.length);
      }
      out.write(_jsp_string99, 0, _jsp_string99.length);
      out.print((CONTEXT_PATH ));
      out.write(_jsp_string100, 0, _jsp_string100.length);
      out.print((CONTEXT_PATH ));
      out.write(_jsp_string101, 0, _jsp_string101.length);
      out.print((CONTEXT_PATH ));
      out.write(_jsp_string102, 0, _jsp_string102.length);
      out.print((CONTEXT_PATH ));
      out.write(_jsp_string103, 0, _jsp_string103.length);
      out.print((CONTEXT_PATH ));
      out.write(_jsp_string104, 0, _jsp_string104.length);
      out.print((CONTEXT_PATH ));
      out.write(_jsp_string105, 0, _jsp_string105.length);
      out.print((CONTEXT_PATH ));
      out.write(_jsp_string106, 0, _jsp_string106.length);
      out.print((CONTEXT_PATH ));
      out.write(_jsp_string107, 0, _jsp_string107.length);
      out.print((CONTEXT_PATH ));
      out.write(_jsp_string108, 0, _jsp_string108.length);
      
    String intervalTime = Context.getSyConf("SY_DESK_MSG_INTERVAL","300000");//\u63d0\u793a\u95f4\u9694\u83b7\u53d6

      out.write(_jsp_string109, 0, _jsp_string109.length);
      out.print((intervalTime));
      out.write(_jsp_string110, 0, _jsp_string110.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7170261747151080670L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sy/comm/desk/desk.jsp"), -5202877845638463301L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sy/base/view/inHeader.jsp"), -8212035121508473076L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string97;
  private final static char []_jsp_string83;
  private final static char []_jsp_string30;
  private final static char []_jsp_string24;
  private final static char []_jsp_string28;
  private final static char []_jsp_string75;
  private final static char []_jsp_string31;
  private final static char []_jsp_string20;
  private final static char []_jsp_string65;
  private final static char []_jsp_string100;
  private final static char []_jsp_string60;
  private final static char []_jsp_string48;
  private final static char []_jsp_string21;
  private final static char []_jsp_string46;
  private final static char []_jsp_string50;
  private final static char []_jsp_string25;
  private final static char []_jsp_string12;
  private final static char []_jsp_string41;
  private final static char []_jsp_string92;
  private final static char []_jsp_string26;
  private final static char []_jsp_string89;
  private final static char []_jsp_string18;
  private final static char []_jsp_string85;
  private final static char []_jsp_string53;
  private final static char []_jsp_string86;
  private final static char []_jsp_string103;
  private final static char []_jsp_string67;
  private final static char []_jsp_string17;
  private final static char []_jsp_string63;
  private final static char []_jsp_string73;
  private final static char []_jsp_string34;
  private final static char []_jsp_string104;
  private final static char []_jsp_string54;
  private final static char []_jsp_string79;
  private final static char []_jsp_string14;
  private final static char []_jsp_string76;
  private final static char []_jsp_string16;
  private final static char []_jsp_string78;
  private final static char []_jsp_string6;
  private final static char []_jsp_string77;
  private final static char []_jsp_string90;
  private final static char []_jsp_string108;
  private final static char []_jsp_string51;
  private final static char []_jsp_string74;
  private final static char []_jsp_string70;
  private final static char []_jsp_string1;
  private final static char []_jsp_string42;
  private final static char []_jsp_string15;
  private final static char []_jsp_string84;
  private final static char []_jsp_string105;
  private final static char []_jsp_string3;
  private final static char []_jsp_string106;
  private final static char []_jsp_string56;
  private final static char []_jsp_string8;
  private final static char []_jsp_string94;
  private final static char []_jsp_string102;
  private final static char []_jsp_string62;
  private final static char []_jsp_string45;
  private final static char []_jsp_string7;
  private final static char []_jsp_string68;
  private final static char []_jsp_string36;
  private final static char []_jsp_string49;
  private final static char []_jsp_string2;
  private final static char []_jsp_string19;
  private final static char []_jsp_string37;
  private final static char []_jsp_string11;
  private final static char []_jsp_string13;
  private final static char []_jsp_string32;
  private final static char []_jsp_string80;
  private final static char []_jsp_string101;
  private final static char []_jsp_string40;
  private final static char []_jsp_string96;
  private final static char []_jsp_string23;
  private final static char []_jsp_string22;
  private final static char []_jsp_string43;
  private final static char []_jsp_string109;
  private final static char []_jsp_string52;
  private final static char []_jsp_string5;
  private final static char []_jsp_string4;
  private final static char []_jsp_string72;
  private final static char []_jsp_string98;
  private final static char []_jsp_string71;
  private final static char []_jsp_string0;
  private final static char []_jsp_string87;
  private final static char []_jsp_string110;
  private final static char []_jsp_string59;
  private final static char []_jsp_string33;
  private final static char []_jsp_string39;
  private final static char []_jsp_string29;
  private final static char []_jsp_string82;
  private final static char []_jsp_string99;
  private final static char []_jsp_string107;
  private final static char []_jsp_string91;
  private final static char []_jsp_string27;
  private final static char []_jsp_string66;
  private final static char []_jsp_string57;
  private final static char []_jsp_string93;
  private final static char []_jsp_string88;
  private final static char []_jsp_string58;
  private final static char []_jsp_string35;
  private final static char []_jsp_string10;
  private final static char []_jsp_string61;
  private final static char []_jsp_string47;
  private final static char []_jsp_string9;
  private final static char []_jsp_string44;
  private final static char []_jsp_string64;
  private final static char []_jsp_string55;
  private final static char []_jsp_string95;
  private final static char []_jsp_string81;
  private final static char []_jsp_string38;
  private final static char []_jsp_string69;
  static {
    _jsp_string97 = ";\r\n		    var loginName = \"".toCharArray();
    _jsp_string83 = "/sy/base/frame/coms/ueditor/editor_config.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string30 = "<!--\u5f00\u53d1\u6a21\u5f0f-->\r\n	<!-- \u5916\u90e8jquery-ui\u5e93\u6837\u5f0f -->\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string24 = "\r\n		<!-- WdatePicker -->\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string28 = "/sy/base/frame/coms/DatePicker/mobileDatePicker/css/mobiscroll.custom-2.6.2.min.css\"/>\r\n		<style>\r\n			.dw-persp {z-index:9999;}\r\n		</style>\r\n	".toCharArray();
    _jsp_string75 = "/sy/base/frame/engines/rhListBatchView.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string31 = "/sy/base/frame/plugs/jquery-ui/jquery.ui.core.css\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string20 = "/sy/base/frame/coms/tree/style.css\"/>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string65 = "/sy/base/frame/coms/rh.ui.search.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string100 = "/sy/comm/desk/css/style.css\" />\r\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string60 = "/sy/base/frame/tools.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string48 = "/sy/base/frame/plugs/jquery-ui/h.jquery.ui.position.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string21 = "/sy/base/frame/coms/tree/jquery.tree.js\"></script>\r\n	<!-- \u672c\u5730\u5b58\u50a8 -->\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string46 = "/sy/base/frame/plugs/jquery-ui/f.jquery.ui.droppable.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string50 = "/sy/base/frame/plugs/jquery-ui/j.jquery.ui.effect.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string25 = "/sy/base/frame/coms/DatePicker/WdatePicker.js\"></script>\r\n	".toCharArray();
    _jsp_string12 = "<!--\u53d1\u5e03\u538b\u7f29\u6587\u4ef6\u6a21\u5f0f-->\r\n	<!-- \u5916\u90e8jquery-ui\u5e93\u6837\u5f0f -->\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string41 = "/sy/base/frame/jquery-1.8.2.min.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string92 = "\";\r\n\r\n    GLOBAL.setFrameId(window.name);//\u8bbe\u7f6e\u5f53\u524dframe\u7684id\u5230\u516c\u5171\u53d8\u91cf\r\n	FireFly.jsessionid = \"".toCharArray();
    _jsp_string26 = "\r\n		<!-- MobiScroll-DatePicker -->\r\n		<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string89 = "\r\n<!-- \u9879\u76ee\u81ea\u5b9a\u4e49css\u6269\u5c55\uff0c\u8bfb\u53d6\u7cfb\u7edf\u914d\u7f6e\u503c\u7684SY_PJ_CSS -->\r\n".toCharArray();
    _jsp_string18 = "/sy/base/frame/jquery-1.8.2.min.js\"></script> \r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string85 = "\r\n<!--\r\n\r\n//-->\r\n</script>\r\n\r\n<!-- \u6253\u5370JS\u5f15\u7528 -->\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string53 = "/sy/base/frame/plugs/jquery-ui/m.jquery.ui.tabs.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string86 = "/sy/print/printThis.js\"></script>\r\n\r\n<!-- \u9879\u76ee\u81ea\u5b9a\u4e49js\u6269\u5c55\uff0c\u8bfb\u53d6\u7cfb\u7edf\u914d\u7f6e\u503c\u7684SY_PJ_JS -->\r\n".toCharArray();
    _jsp_string103 = "/sy/comm/desk/js/lang_js.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string67 = "/sy/base/frame/coms/rh.ui.Delegate.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string17 = "\r\n	<!-- \u5916\u90e8jquery-ui\u5e93js\u811a\u672c -->\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string63 = "/sy/base/frame/coms/rh.ui.menu.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string73 = "/sy/base/frame/coms/rh.ui.next.js\"></script>\r\n	<!-- \u5e73\u53f0UI\u6838\u5fc3view\u90e8\u5206js\u5e93 -->\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string34 = "/sy/theme/default/base.css\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string104 = "/sy/comm/desk/js/jquery.ux.borderlayout.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string54 = "/sy/base/frame/plugs/jquery-ui/n.jquery.validate.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string79 = "/sy/base/frame/engines/rhWfCardView.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string14 = "/sy/theme/default/rh.core.min.css\"/> \r\n	".toCharArray();
    _jsp_string76 = "/sy/base/frame/engines/rhCardView.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string16 = "/sy/theme/default/fontBig.css\"/>\r\n	".toCharArray();
    _jsp_string78 = "/sy/base/frame/engines/rhSelectListView.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string6 = "\r\n	<meta name=\"viewport\" content=\"width=1100\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string77 = "/sy/base/frame/engines/rhDictTreeView.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string90 = "\"/>\r\n".toCharArray();
    _jsp_string108 = "/sy/comm/desk/js/rhDeskView.js\"></script>\r\n</head>\r\n".toCharArray();
    _jsp_string51 = "/sy/base/frame/plugs/jquery-ui/k.jquery.ui.accordion.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string74 = "/sy/base/frame/engines/rhListView.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string70 = "/sy/base/frame/coms/rh.ui.popPrompt.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string1 = "\r\n<head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n    <title>\u56fe\u6807\u5316\u9996\u9875</title>\r\n    \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string42 = "/sy/base/frame/plugs/jquery-ui/a.jquery.ui.core.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string15 = "\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string84 = "/sy/base/frame/coms/ueditor/editor_all.js\"></script>	\r\n	".toCharArray();
    _jsp_string105 = "/sy/comm/desk/js/jquery.ux.slidebox.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string3 = "\"/>\r\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n".toCharArray();
    _jsp_string106 = "/sy/comm/desk/js/jquery.ux.simulatemouse.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string56 = "/sy/base/frame/coms/rh.ui.base64.js\"></script>\r\n	<!-- \u672c\u5730\u5b58\u50a8 -->\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string8 = "\r\n	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string94 = "\";\r\n	".toCharArray();
    _jsp_string102 = "/sy/comm/desk/js/jquery.ui.sortable.min.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string62 = "/sy/base/frame/coms/rh.ui.grid.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string45 = "/sy/base/frame/plugs/jquery-ui/e.jquery.ui.draggable.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string7 = "/sy/theme/default/pad-extend.css\"/>\r\n".toCharArray();
    _jsp_string68 = "/sy/base/frame/coms/rh.ui.openTab.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string36 = "/sy/theme/default/page.css\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string49 = "/sy/base/frame/plugs/jquery-ui/i.jquery.ui.resizable.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string2 = "\r\n<meta name=\"servName\" content=\"".toCharArray();
    _jsp_string19 = "/sy/base/frame/plugs/jquery-ui/rh.jquery-ui.min.js\"></script>\r\n	<!-- \u5916\u90e8jquerytree\u5e93js\u811a\u672c -->\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string37 = "/sy/theme/default/form.css\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string11 = "\";//\u865a\u62df\u8def\u5f84\r\n</script>\r\n".toCharArray();
    _jsp_string13 = "/sy/base/frame/plugs/jquery-ui/rh.jquery-ui.min.css\"/>  \r\n	<!-- \u5e73\u53f0UI\u6838\u5fc3\u6837\u5f0f -->\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string32 = "/sy/base/frame/plugs/jquery-ui/jquery.ui.resizable.css\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string80 = "/sy/base/frame/engines/rhUserInfoView.js\"></script>	\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string101 = "/sy/comm/desk/css/desk.css\" />\r\n    <script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string40 = "/sy/base/frame/coms/tree/style.css\"/><!-- \u5916\u90e8jquerytree\u5e93js\u811a\u672c -->\r\n    ".toCharArray();
    _jsp_string96 = "\r\n			var sysVarParasStr = ".toCharArray();
    _jsp_string23 = "/sy/base/frame/rh.core.min.js\"></script>\r\n	".toCharArray();
    _jsp_string22 = "/sy/base/frame/store.min.js\"></script>\r\n	<!-- \u5e73\u53f0UI\u6838\u5fc3js\u5e93 -->\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string43 = "/sy/base/frame/plugs/jquery-ui/b.jquery.ui.widget.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string109 = "\r\n<body  style=\"background:#5a97d6;\">\r\n	<div class=\"slidebox\">\r\n	  	<div id=\"container\"></div>\r\n	</div>\r\n	<div id=\"overlay\"></div>\r\n\r\n	<div class=\"background\" style=\"\"></div>\r\n\r\n	\r\n	<div id=\"control\"> \r\n      <table align=\"center\">\r\n         <tr>\r\n            <td class=\"control-l\"><a id=\"openSearch\" title=\"\u6253\u5f00\u641c\u7d22\u6846\" href=\"javascript:void(0);\" class=\"rh-slide-search\"></a></td>\r\n            <td class=\"control-c\"></td>\r\n            <td class=\"control-r\"><a id=\"openAppBox\" title=\"\u6253\u5f00\u5e94\u7528\u76d2\u5b50\" href=\"javascript: void(0)\" class=\"cfg\"></a> </td>\r\n         </tr>\r\n      </table>\r\n   </div>\r\n	<div class=\"bottom-normal\" id=\"normalUse\" align=center>\r\n      <table align=\"center\">\r\n         <tr align=center>\r\n            <td class=\"normalUse-l\"></td>\r\n            <td class=\"normalUse-c\" align=center></td>\r\n            <td class=\"normalUse-r\"><div id=\"trash\"></div></td>\r\n         </tr>\r\n      </table>\r\n	</div>\r\n<script type=\"text/javascript\">\r\n var deskView = new rh.vi.deskView({\"id\":\"rh\",\"intervalTime\":\"".toCharArray();
    _jsp_string52 = "/sy/base/frame/plugs/jquery-ui/l.jquery.ui.dialog.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string5 = "/sy/theme/default/mob-extend.css\"/>\r\n".toCharArray();
    _jsp_string4 = "\r\n	<meta name=\"viewport\" content=\"width=1280\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string72 = "/sy/base/frame/coms/rh.ui.mind.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string98 = "\";\r\n	\r\n			var devUsersArray = devUsers.split(\",\");\r\n			if (jQuery.inArray(loginName,devUsersArray) != -1) {\r\n				sysVarParasStr[\"@DEV_FLAG@\"] = \"true\";\r\n			}\r\n			System.setVars(sysVarParasStr);\r\n	    } else {\r\n	    	System.setVars(parSysVars);\r\n	    }\r\n		GLOBAL.cookieBanner = \"rh_banner_\" + \"".toCharArray();
    _jsp_string71 = "/sy/base/frame/coms/rh.ui.card.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string0 = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<!--desk.jsp\u00e9\u00a6\u0096\u00e9\u00a1\u00b5\u00e9\u009d\u00a2-->\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n".toCharArray();
    _jsp_string87 = "\r\n    <script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string110 = "\"});\r\n deskView.show();\r\n</script>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string59 = "/sy/base/frame/platform.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string33 = "/sy/base/frame/plugs/jquery-ui/jquery.ui.theme.css\"/>\r\n	<!-- \u5e73\u53f0UI\u6838\u5fc3\u6837\u5f0f -->\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string39 = "/sy/theme/default/colortip.css\"/><!-- \u63d0\u793a\u4fe1\u606f -->\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string29 = "\r\n".toCharArray();
    _jsp_string82 = "/sy/base/frame/engines/rhCommentView.js\"></script>\r\n	<!-- UEditor -->\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string99 = "\r\n</script>\r\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string107 = "/sy/comm/desk/js/reflection.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string91 = "\r\n<script type=\"text/javascript\">\r\n	var __SERVER_NAME = \"".toCharArray();
    _jsp_string27 = "/sy/base/frame/coms/DatePicker/mobileDatePicker/js/mobiscroll.custom-2.6.2.min.js\"></script>\r\n		<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string66 = "/sy/base/frame/coms/rh.ui.tree.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string57 = "/sy/base/frame/store.min.js\"></script>\r\n	<!-- \u5916\u90e8jquerytree\u5e93js\u811a\u672c -->\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string93 = "\";\r\n	var devUsers = \"".toCharArray();
    _jsp_string88 = "\"></script>\r\n".toCharArray();
    _jsp_string58 = "/sy/base/frame/coms/tree/jquery.tree.js\"></script>\r\n	<!-- \u5e73\u53f0UI\u6838\u5fc3js\u5e93 -->\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string35 = "/sy/theme/default/common.css\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string10 = "\r\n<script type=\"text/javascript\">\r\n	var FireFlyContextPath = \"".toCharArray();
    _jsp_string61 = "/sy/base/frame/constant.js\"></script>\r\n	<!-- \u5e73\u53f0UI\u6838\u5fc3\u7ec4\u4ef6js\u5e93 -->\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string47 = "/sy/base/frame/plugs/jquery-ui/g.jquery.ui.sortable.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string9 = "/sy/theme/default/pc-extend.css\"/>\r\n".toCharArray();
    _jsp_string44 = "/sy/base/frame/plugs/jquery-ui/d.jquery.ui.mouse.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string64 = "/sy/base/frame/coms/rh.ui.loadbar.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string55 = "/sy/base/frame/coms/rh.ui.colorTip.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string95 = "\r\n	    var parSysVars = {};\r\n	    try {\r\n		    if (parent && parent.System) {\r\n	            var innerPath = FireFly.getHttpHost() + FireFlyContextPath;\r\n		    	var parPath = parent.FireFly.getHttpHost() + parent.FireFlyContextPath;\r\n		    	if (innerPath == parPath) {\r\n			    	parSysVars = parent.System.getVars();\r\n		    	}\r\n			}\r\n		} catch(e) {\r\n		}\r\n	    if (jQuery.isEmptyObject(parSysVars)) {\r\n			".toCharArray();
    _jsp_string81 = "/sy/base/frame/engines/rhListExpanderView.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string38 = "/sy/theme/default/icon.css\"/>\r\n	<link rel=\"stylesheet\" type=\"text/css\" href=\"".toCharArray();
    _jsp_string69 = "/sy/base/frame/coms/rh.ui.pop.js\"></script>\r\n	<script type=\"text/javascript\" src=\"".toCharArray();
  }
}
